### ISSUE TITLE
Updated script?

### ISSUE THREAD

**Issue by carmerlun** [SevillaR/Andaclima#1]
Dear Andaclima contributors,

I wanted to use your script to download climatic data from IFAPA website. However, I noticed that the script assumes a zip file to be obtained from the website when currently it directly offers a CSV. Also, using R version 4.0.4 and Rstudio version 2022.7.2, I got this error: 

Error in file(con, "wb") : cannot open the connection
In addition: Warning message:
In file(con, "wb") :
   Error in file(con, "wb") : cannot open the connection

Is there an updated version of this script? Thank you very much in advance.

**Comment by Pakillo** [comment]
Hi @carmerlun 

This package was developed at a SevillaR hackathon but has since been abandoned. It might be reactivated in the future, but meanwhile I'd suggest trying the meteospain package which can download data from the Andalusian Agroclimatic network, among others: https://emf-creaf.github.io/meteospain/

Good luck!

**Comment by carmerlun** [comment]
Thank you very much @Pakillo , the package you recommened works nicely!

**Comment by Pakillo** [comment]
Good to know, thanks!
